version: '3.7'

services:
  db:
    build: ./postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - house
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: house

  adminer:
    image: adminer
    restart: always
    networks:
      - house
    ports:
      - 8080:8080

networks:
  house:

volumes:
  db-data: