const mbxClient = require('@mapbox/mapbox-sdk');
const mbxStyles = require('@mapbox/mapbox-sdk/services/styles');
const fs = require('fs');

/* This token only has read permissions.  It's fine to make it public. */
const MAPBOX_TOKEN = 'sk.eyJ1IjoiZHNoZWFyZXIiLCJhIjoiY2szeGp4aDNyMWFpODNtbzE2OHowb2FldCJ9.aCPGbAHjqXdyj2lyDsi7xg';

const MAPBOX_BASE_CLIENT = mbxClient({ accessToken: MAPBOX_TOKEN });
const MAPBOX_STYLES_CLIENT = mbxStyles(MAPBOX_BASE_CLIENT);

const GEN_CODE_COMMENT = `/* Generated by get-styles.js */`

// get map styles
MAPBOX_STYLES_CLIENT.listStyles()
    .send({ownerId: 'dshearer'})
    .then(resp => {
        // find relevant styles
        const congressNbrToStyleId = {};
        resp.body.forEach(style => {
            if (!style.name.startsWith('congress-')) {
                return;
            }
            const parts = style.name.split('-');
            const congressNbr = parts[1];
            congressNbrToStyleId[congressNbr] = style.id;
        });

        // save styles to JSON doc
        const s = JSON.stringify(congressNbrToStyleId, undefined, 0);
        const code = `${GEN_CODE_COMMENT}
        const A = ${s};
        export default A;`;
        fs.writeFileSync('src/congressNbrToStyleId.js', code);
    })
    .catch(e => {
        console.log(e.message);
        process.exit(1);
    });
